### ISSUE TITLE
how do i download the files or where do i find them

### ISSUE THREAD

**Issue by lamsoos** [ryan5453/demucs-cog#1]
![image](https://user-images.githubusercontent.com/119911536/205810030-b137f734-ea37-436c-bbd7-98378a377ed4.png)
i tried pressing the link thingy but all it did was download a file like a plain file... please help

**Comment by ryan5453** [comment]
The plain file is the audio file. You either can add .wav or .mp3 to the end of the file name depending on the parameters you selected.

**Comment by lamsoos** [comment]
thanks
